//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopDiary.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public int IdStatus { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string Descrip { get; set; }
    
        public virtual StatusRequest StatusRequest { get; set; }
    }
}
